#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCatalogue.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProductCatalogue3")]
	public partial class ResearchDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccommodationOccupancy(AccommodationOccupancy instance);
    partial void UpdateAccommodationOccupancy(AccommodationOccupancy instance);
    partial void DeleteAccommodationOccupancy(AccommodationOccupancy instance);
    partial void InsertCampgroundOccupancy(CampgroundOccupancy instance);
    partial void UpdateCampgroundOccupancy(CampgroundOccupancy instance);
    partial void DeleteCampgroundOccupancy(CampgroundOccupancy instance);
    #endregion
		
		public ResearchDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResearchDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResearchDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResearchDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AccommodationOccupancy> AccommodationOccupancies
		{
			get
			{
				return this.GetTable<AccommodationOccupancy>();
			}
		}
		
		public System.Data.Linq.Table<CampgroundOccupancy> CampgroundOccupancies
		{
			get
			{
				return this.GetTable<CampgroundOccupancy>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetVarianceReport")]
		public ISingleResult<GetVarianceReportResult> GetVarianceReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> startMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> startYear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> endMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> endYear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> variance, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> varianceByAmount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startMonth, startYear, endMonth, endYear, variance, varianceByAmount);
			return ((ISingleResult<GetVarianceReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCampVarianceReport")]
		public ISingleResult<GetCampVarianceReportResult> GetCampVarianceReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> startMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> startYear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> endMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> endYear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> variance, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> varianceByAmount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startMonth, startYear, endMonth, endYear, variance, varianceByAmount);
			return ((ISingleResult<GetCampVarianceReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CalculateOpenProperties")]
		public ISingleResult<CalculateOpenPropertiesResult> CalculateOpenProperties([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> reportDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string productIds)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportDate, productIds);
			return ((ISingleResult<CalculateOpenPropertiesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccommodationOccupancy")]
	public partial class AccommodationOccupancy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productId;
		
		private System.DateTime _reportDate;
		
		private string _licenseNumber;
		
		private System.Nullable<byte> _accommodationTypeId;
		
		private System.Nullable<byte> _starClassRating;
		
		private byte _daysOpen;
		
		private short _unitsAvailable;
		
		private System.Nullable<short> _totalUnitsSold;
		
		private System.Nullable<int> _totalGuests;
		
		private System.Nullable<byte> _vacationPct;
		
		private System.Nullable<byte> _businessPct;
		
		private System.Nullable<byte> _conventionPct;
		
		private System.Nullable<byte> _motorcoachPct;
		
		private System.Nullable<byte> _otherPct;
		
		private System.Nullable<System.DateTime> _lastModifiedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIdChanging(int value);
    partial void OnproductIdChanged();
    partial void OnreportDateChanging(System.DateTime value);
    partial void OnreportDateChanged();
    partial void OnlicenseNumberChanging(string value);
    partial void OnlicenseNumberChanged();
    partial void OnaccommodationTypeIdChanging(System.Nullable<byte> value);
    partial void OnaccommodationTypeIdChanged();
    partial void OnstarClassRatingChanging(System.Nullable<byte> value);
    partial void OnstarClassRatingChanged();
    partial void OndaysOpenChanging(byte value);
    partial void OndaysOpenChanged();
    partial void OnunitsAvailableChanging(short value);
    partial void OnunitsAvailableChanged();
    partial void OntotalUnitsSoldChanging(System.Nullable<short> value);
    partial void OntotalUnitsSoldChanged();
    partial void OntotalGuestsChanging(System.Nullable<int> value);
    partial void OntotalGuestsChanged();
    partial void OnvacationPctChanging(System.Nullable<byte> value);
    partial void OnvacationPctChanged();
    partial void OnbusinessPctChanging(System.Nullable<byte> value);
    partial void OnbusinessPctChanged();
    partial void OnconventionPctChanging(System.Nullable<byte> value);
    partial void OnconventionPctChanged();
    partial void OnmotorcoachPctChanging(System.Nullable<byte> value);
    partial void OnmotorcoachPctChanged();
    partial void OnotherPctChanging(System.Nullable<byte> value);
    partial void OnotherPctChanged();
    partial void OnlastModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastModifiedDateChanged();
    #endregion
		
		public AccommodationOccupancy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int productId
		{
			get
			{
				return this._productId;
			}
			set
			{
				if ((this._productId != value))
				{
					this.OnproductIdChanging(value);
					this.SendPropertyChanging();
					this._productId = value;
					this.SendPropertyChanged("productId");
					this.OnproductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reportDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime reportDate
		{
			get
			{
				return this._reportDate;
			}
			set
			{
				if ((this._reportDate != value))
				{
					this.OnreportDateChanging(value);
					this.SendPropertyChanging();
					this._reportDate = value;
					this.SendPropertyChanged("reportDate");
					this.OnreportDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseNumber", DbType="VarChar(50)")]
		public string licenseNumber
		{
			get
			{
				return this._licenseNumber;
			}
			set
			{
				if ((this._licenseNumber != value))
				{
					this.OnlicenseNumberChanging(value);
					this.SendPropertyChanging();
					this._licenseNumber = value;
					this.SendPropertyChanged("licenseNumber");
					this.OnlicenseNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accommodationTypeId", DbType="TinyInt")]
		public System.Nullable<byte> accommodationTypeId
		{
			get
			{
				return this._accommodationTypeId;
			}
			set
			{
				if ((this._accommodationTypeId != value))
				{
					this.OnaccommodationTypeIdChanging(value);
					this.SendPropertyChanging();
					this._accommodationTypeId = value;
					this.SendPropertyChanged("accommodationTypeId");
					this.OnaccommodationTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starClassRating", DbType="TinyInt")]
		public System.Nullable<byte> starClassRating
		{
			get
			{
				return this._starClassRating;
			}
			set
			{
				if ((this._starClassRating != value))
				{
					this.OnstarClassRatingChanging(value);
					this.SendPropertyChanging();
					this._starClassRating = value;
					this.SendPropertyChanged("starClassRating");
					this.OnstarClassRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daysOpen", DbType="TinyInt NOT NULL")]
		public byte daysOpen
		{
			get
			{
				return this._daysOpen;
			}
			set
			{
				if ((this._daysOpen != value))
				{
					this.OndaysOpenChanging(value);
					this.SendPropertyChanging();
					this._daysOpen = value;
					this.SendPropertyChanged("daysOpen");
					this.OndaysOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitsAvailable", DbType="SmallInt NOT NULL")]
		public short unitsAvailable
		{
			get
			{
				return this._unitsAvailable;
			}
			set
			{
				if ((this._unitsAvailable != value))
				{
					this.OnunitsAvailableChanging(value);
					this.SendPropertyChanging();
					this._unitsAvailable = value;
					this.SendPropertyChanged("unitsAvailable");
					this.OnunitsAvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalUnitsSold", DbType="SmallInt")]
		public System.Nullable<short> totalUnitsSold
		{
			get
			{
				return this._totalUnitsSold;
			}
			set
			{
				if ((this._totalUnitsSold != value))
				{
					this.OntotalUnitsSoldChanging(value);
					this.SendPropertyChanging();
					this._totalUnitsSold = value;
					this.SendPropertyChanged("totalUnitsSold");
					this.OntotalUnitsSoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalGuests", DbType="Int")]
		public System.Nullable<int> totalGuests
		{
			get
			{
				return this._totalGuests;
			}
			set
			{
				if ((this._totalGuests != value))
				{
					this.OntotalGuestsChanging(value);
					this.SendPropertyChanging();
					this._totalGuests = value;
					this.SendPropertyChanged("totalGuests");
					this.OntotalGuestsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vacationPct", DbType="TinyInt")]
		public System.Nullable<byte> vacationPct
		{
			get
			{
				return this._vacationPct;
			}
			set
			{
				if ((this._vacationPct != value))
				{
					this.OnvacationPctChanging(value);
					this.SendPropertyChanging();
					this._vacationPct = value;
					this.SendPropertyChanged("vacationPct");
					this.OnvacationPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_businessPct", DbType="TinyInt")]
		public System.Nullable<byte> businessPct
		{
			get
			{
				return this._businessPct;
			}
			set
			{
				if ((this._businessPct != value))
				{
					this.OnbusinessPctChanging(value);
					this.SendPropertyChanging();
					this._businessPct = value;
					this.SendPropertyChanged("businessPct");
					this.OnbusinessPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conventionPct", DbType="TinyInt")]
		public System.Nullable<byte> conventionPct
		{
			get
			{
				return this._conventionPct;
			}
			set
			{
				if ((this._conventionPct != value))
				{
					this.OnconventionPctChanging(value);
					this.SendPropertyChanging();
					this._conventionPct = value;
					this.SendPropertyChanged("conventionPct");
					this.OnconventionPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motorcoachPct", DbType="TinyInt")]
		public System.Nullable<byte> motorcoachPct
		{
			get
			{
				return this._motorcoachPct;
			}
			set
			{
				if ((this._motorcoachPct != value))
				{
					this.OnmotorcoachPctChanging(value);
					this.SendPropertyChanging();
					this._motorcoachPct = value;
					this.SendPropertyChanged("motorcoachPct");
					this.OnmotorcoachPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherPct", DbType="TinyInt")]
		public System.Nullable<byte> otherPct
		{
			get
			{
				return this._otherPct;
			}
			set
			{
				if ((this._otherPct != value))
				{
					this.OnotherPctChanging(value);
					this.SendPropertyChanging();
					this._otherPct = value;
					this.SendPropertyChanged("otherPct");
					this.OnotherPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastModifiedDate
		{
			get
			{
				return this._lastModifiedDate;
			}
			set
			{
				if ((this._lastModifiedDate != value))
				{
					this.OnlastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._lastModifiedDate = value;
					this.SendPropertyChanged("lastModifiedDate");
					this.OnlastModifiedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CampgroundOccupancy")]
	public partial class CampgroundOccupancy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productId;
		
		private System.DateTime _reportDate;
		
		private string _licenseNumber;
		
		private System.Nullable<byte> _campgroundTypeId;
		
		private System.Nullable<byte> _starClassRating;
		
		private byte _daysOpen;
		
		private short _seasonalAvailable;
		
		private short _shortTermAvailable;
		
		private System.Nullable<int> _seasonalSold;
		
		private System.Nullable<int> _shortTermSold;
		
		private System.Nullable<int> _totalGuests;
		
		private System.Nullable<int> _nsTents;
		
		private System.Nullable<int> _canTents;
		
		private System.Nullable<int> _usTents;
		
		private System.Nullable<int> _intTents;
		
		private System.Nullable<int> _nsRvs;
		
		private System.Nullable<int> _canRvs;
		
		private System.Nullable<int> _usRvs;
		
		private System.Nullable<int> _intRvs;
		
		private System.Nullable<int> _nsCabins;
		
		private System.Nullable<int> _canCabins;
		
		private System.Nullable<int> _usCabins;
		
		private System.Nullable<int> _intCabins;
		
		private System.Nullable<System.DateTime> _lastModifiedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIdChanging(int value);
    partial void OnproductIdChanged();
    partial void OnreportDateChanging(System.DateTime value);
    partial void OnreportDateChanged();
    partial void OnlicenseNumberChanging(string value);
    partial void OnlicenseNumberChanged();
    partial void OncampgroundTypeIdChanging(System.Nullable<byte> value);
    partial void OncampgroundTypeIdChanged();
    partial void OnstarClassRatingChanging(System.Nullable<byte> value);
    partial void OnstarClassRatingChanged();
    partial void OndaysOpenChanging(byte value);
    partial void OndaysOpenChanged();
    partial void OnseasonalAvailableChanging(short value);
    partial void OnseasonalAvailableChanged();
    partial void OnshortTermAvailableChanging(short value);
    partial void OnshortTermAvailableChanged();
    partial void OnseasonalSoldChanging(System.Nullable<int> value);
    partial void OnseasonalSoldChanged();
    partial void OnshortTermSoldChanging(System.Nullable<int> value);
    partial void OnshortTermSoldChanged();
    partial void OntotalGuestsChanging(System.Nullable<int> value);
    partial void OntotalGuestsChanged();
    partial void OnnsTentsChanging(System.Nullable<int> value);
    partial void OnnsTentsChanged();
    partial void OncanTentsChanging(System.Nullable<int> value);
    partial void OncanTentsChanged();
    partial void OnusTentsChanging(System.Nullable<int> value);
    partial void OnusTentsChanged();
    partial void OnintTentsChanging(System.Nullable<int> value);
    partial void OnintTentsChanged();
    partial void OnnsRvsChanging(System.Nullable<int> value);
    partial void OnnsRvsChanged();
    partial void OncanRvsChanging(System.Nullable<int> value);
    partial void OncanRvsChanged();
    partial void OnusRvsChanging(System.Nullable<int> value);
    partial void OnusRvsChanged();
    partial void OnintRvsChanging(System.Nullable<int> value);
    partial void OnintRvsChanged();
    partial void OnnsCabinsChanging(System.Nullable<int> value);
    partial void OnnsCabinsChanged();
    partial void OncanCabinsChanging(System.Nullable<int> value);
    partial void OncanCabinsChanged();
    partial void OnusCabinsChanging(System.Nullable<int> value);
    partial void OnusCabinsChanged();
    partial void OnintCabinsChanging(System.Nullable<int> value);
    partial void OnintCabinsChanged();
    partial void OnlastModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastModifiedDateChanged();
    #endregion
		
		public CampgroundOccupancy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int productId
		{
			get
			{
				return this._productId;
			}
			set
			{
				if ((this._productId != value))
				{
					this.OnproductIdChanging(value);
					this.SendPropertyChanging();
					this._productId = value;
					this.SendPropertyChanged("productId");
					this.OnproductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reportDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime reportDate
		{
			get
			{
				return this._reportDate;
			}
			set
			{
				if ((this._reportDate != value))
				{
					this.OnreportDateChanging(value);
					this.SendPropertyChanging();
					this._reportDate = value;
					this.SendPropertyChanged("reportDate");
					this.OnreportDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseNumber", DbType="VarChar(50)")]
		public string licenseNumber
		{
			get
			{
				return this._licenseNumber;
			}
			set
			{
				if ((this._licenseNumber != value))
				{
					this.OnlicenseNumberChanging(value);
					this.SendPropertyChanging();
					this._licenseNumber = value;
					this.SendPropertyChanged("licenseNumber");
					this.OnlicenseNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campgroundTypeId", DbType="TinyInt")]
		public System.Nullable<byte> campgroundTypeId
		{
			get
			{
				return this._campgroundTypeId;
			}
			set
			{
				if ((this._campgroundTypeId != value))
				{
					this.OncampgroundTypeIdChanging(value);
					this.SendPropertyChanging();
					this._campgroundTypeId = value;
					this.SendPropertyChanged("campgroundTypeId");
					this.OncampgroundTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starClassRating", DbType="TinyInt")]
		public System.Nullable<byte> starClassRating
		{
			get
			{
				return this._starClassRating;
			}
			set
			{
				if ((this._starClassRating != value))
				{
					this.OnstarClassRatingChanging(value);
					this.SendPropertyChanging();
					this._starClassRating = value;
					this.SendPropertyChanged("starClassRating");
					this.OnstarClassRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daysOpen", DbType="TinyInt NOT NULL")]
		public byte daysOpen
		{
			get
			{
				return this._daysOpen;
			}
			set
			{
				if ((this._daysOpen != value))
				{
					this.OndaysOpenChanging(value);
					this.SendPropertyChanging();
					this._daysOpen = value;
					this.SendPropertyChanged("daysOpen");
					this.OndaysOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seasonalAvailable", DbType="SmallInt NOT NULL")]
		public short seasonalAvailable
		{
			get
			{
				return this._seasonalAvailable;
			}
			set
			{
				if ((this._seasonalAvailable != value))
				{
					this.OnseasonalAvailableChanging(value);
					this.SendPropertyChanging();
					this._seasonalAvailable = value;
					this.SendPropertyChanged("seasonalAvailable");
					this.OnseasonalAvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortTermAvailable", DbType="SmallInt NOT NULL")]
		public short shortTermAvailable
		{
			get
			{
				return this._shortTermAvailable;
			}
			set
			{
				if ((this._shortTermAvailable != value))
				{
					this.OnshortTermAvailableChanging(value);
					this.SendPropertyChanging();
					this._shortTermAvailable = value;
					this.SendPropertyChanged("shortTermAvailable");
					this.OnshortTermAvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seasonalSold", DbType="Int")]
		public System.Nullable<int> seasonalSold
		{
			get
			{
				return this._seasonalSold;
			}
			set
			{
				if ((this._seasonalSold != value))
				{
					this.OnseasonalSoldChanging(value);
					this.SendPropertyChanging();
					this._seasonalSold = value;
					this.SendPropertyChanged("seasonalSold");
					this.OnseasonalSoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortTermSold", DbType="Int")]
		public System.Nullable<int> shortTermSold
		{
			get
			{
				return this._shortTermSold;
			}
			set
			{
				if ((this._shortTermSold != value))
				{
					this.OnshortTermSoldChanging(value);
					this.SendPropertyChanging();
					this._shortTermSold = value;
					this.SendPropertyChanged("shortTermSold");
					this.OnshortTermSoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalGuests", DbType="Int")]
		public System.Nullable<int> totalGuests
		{
			get
			{
				return this._totalGuests;
			}
			set
			{
				if ((this._totalGuests != value))
				{
					this.OntotalGuestsChanging(value);
					this.SendPropertyChanging();
					this._totalGuests = value;
					this.SendPropertyChanged("totalGuests");
					this.OntotalGuestsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsTents", DbType="Int")]
		public System.Nullable<int> nsTents
		{
			get
			{
				return this._nsTents;
			}
			set
			{
				if ((this._nsTents != value))
				{
					this.OnnsTentsChanging(value);
					this.SendPropertyChanging();
					this._nsTents = value;
					this.SendPropertyChanged("nsTents");
					this.OnnsTentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canTents", DbType="Int")]
		public System.Nullable<int> canTents
		{
			get
			{
				return this._canTents;
			}
			set
			{
				if ((this._canTents != value))
				{
					this.OncanTentsChanging(value);
					this.SendPropertyChanging();
					this._canTents = value;
					this.SendPropertyChanged("canTents");
					this.OncanTentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usTents", DbType="Int")]
		public System.Nullable<int> usTents
		{
			get
			{
				return this._usTents;
			}
			set
			{
				if ((this._usTents != value))
				{
					this.OnusTentsChanging(value);
					this.SendPropertyChanging();
					this._usTents = value;
					this.SendPropertyChanged("usTents");
					this.OnusTentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTents", DbType="Int")]
		public System.Nullable<int> intTents
		{
			get
			{
				return this._intTents;
			}
			set
			{
				if ((this._intTents != value))
				{
					this.OnintTentsChanging(value);
					this.SendPropertyChanging();
					this._intTents = value;
					this.SendPropertyChanged("intTents");
					this.OnintTentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsRvs", DbType="Int")]
		public System.Nullable<int> nsRvs
		{
			get
			{
				return this._nsRvs;
			}
			set
			{
				if ((this._nsRvs != value))
				{
					this.OnnsRvsChanging(value);
					this.SendPropertyChanging();
					this._nsRvs = value;
					this.SendPropertyChanged("nsRvs");
					this.OnnsRvsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canRvs", DbType="Int")]
		public System.Nullable<int> canRvs
		{
			get
			{
				return this._canRvs;
			}
			set
			{
				if ((this._canRvs != value))
				{
					this.OncanRvsChanging(value);
					this.SendPropertyChanging();
					this._canRvs = value;
					this.SendPropertyChanged("canRvs");
					this.OncanRvsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usRvs", DbType="Int")]
		public System.Nullable<int> usRvs
		{
			get
			{
				return this._usRvs;
			}
			set
			{
				if ((this._usRvs != value))
				{
					this.OnusRvsChanging(value);
					this.SendPropertyChanging();
					this._usRvs = value;
					this.SendPropertyChanged("usRvs");
					this.OnusRvsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intRvs", DbType="Int")]
		public System.Nullable<int> intRvs
		{
			get
			{
				return this._intRvs;
			}
			set
			{
				if ((this._intRvs != value))
				{
					this.OnintRvsChanging(value);
					this.SendPropertyChanging();
					this._intRvs = value;
					this.SendPropertyChanged("intRvs");
					this.OnintRvsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsCabins", DbType="Int")]
		public System.Nullable<int> nsCabins
		{
			get
			{
				return this._nsCabins;
			}
			set
			{
				if ((this._nsCabins != value))
				{
					this.OnnsCabinsChanging(value);
					this.SendPropertyChanging();
					this._nsCabins = value;
					this.SendPropertyChanged("nsCabins");
					this.OnnsCabinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canCabins", DbType="Int")]
		public System.Nullable<int> canCabins
		{
			get
			{
				return this._canCabins;
			}
			set
			{
				if ((this._canCabins != value))
				{
					this.OncanCabinsChanging(value);
					this.SendPropertyChanging();
					this._canCabins = value;
					this.SendPropertyChanged("canCabins");
					this.OncanCabinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usCabins", DbType="Int")]
		public System.Nullable<int> usCabins
		{
			get
			{
				return this._usCabins;
			}
			set
			{
				if ((this._usCabins != value))
				{
					this.OnusCabinsChanging(value);
					this.SendPropertyChanging();
					this._usCabins = value;
					this.SendPropertyChanged("usCabins");
					this.OnusCabinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCabins", DbType="Int")]
		public System.Nullable<int> intCabins
		{
			get
			{
				return this._intCabins;
			}
			set
			{
				if ((this._intCabins != value))
				{
					this.OnintCabinsChanging(value);
					this.SendPropertyChanging();
					this._intCabins = value;
					this.SendPropertyChanged("intCabins");
					this.OnintCabinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastModifiedDate
		{
			get
			{
				return this._lastModifiedDate;
			}
			set
			{
				if ((this._lastModifiedDate != value))
				{
					this.OnlastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._lastModifiedDate = value;
					this.SendPropertyChanged("lastModifiedDate");
					this.OnlastModifiedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetVarianceReportResult
	{
		
		private int _id;
		
		private string _licenseNumber;
		
		private string _productName;
		
		private string _communityName;
		
		private string _regionName;
		
		private System.Nullable<short> _startUnitsSold;
		
		private System.Nullable<short> _endUnitsSold;
		
		private System.Nullable<decimal> _percentageDifference;
		
		private System.Nullable<short> _amountDifference;
		
		public GetVarianceReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseNumber", DbType="VarChar(50)")]
		public string licenseNumber
		{
			get
			{
				return this._licenseNumber;
			}
			set
			{
				if ((this._licenseNumber != value))
				{
					this._licenseNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if ((this._productName != value))
				{
					this._productName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_communityName", DbType="VarChar(50)")]
		public string communityName
		{
			get
			{
				return this._communityName;
			}
			set
			{
				if ((this._communityName != value))
				{
					this._communityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionName", DbType="VarChar(100)")]
		public string regionName
		{
			get
			{
				return this._regionName;
			}
			set
			{
				if ((this._regionName != value))
				{
					this._regionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startUnitsSold", DbType="SmallInt")]
		public System.Nullable<short> startUnitsSold
		{
			get
			{
				return this._startUnitsSold;
			}
			set
			{
				if ((this._startUnitsSold != value))
				{
					this._startUnitsSold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endUnitsSold", DbType="SmallInt")]
		public System.Nullable<short> endUnitsSold
		{
			get
			{
				return this._endUnitsSold;
			}
			set
			{
				if ((this._endUnitsSold != value))
				{
					this._endUnitsSold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentageDifference", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> percentageDifference
		{
			get
			{
				return this._percentageDifference;
			}
			set
			{
				if ((this._percentageDifference != value))
				{
					this._percentageDifference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountDifference", DbType="SmallInt")]
		public System.Nullable<short> amountDifference
		{
			get
			{
				return this._amountDifference;
			}
			set
			{
				if ((this._amountDifference != value))
				{
					this._amountDifference = value;
				}
			}
		}
	}
	
	public partial class GetCampVarianceReportResult
	{
		
		private int _id;
		
		private string _licenseNumber;
		
		private string _productName;
		
		private string _communityName;
		
		private string _regionName;
		
		private System.Nullable<int> _startUnitsSold;
		
		private System.Nullable<int> _endUnitsSold;
		
		private System.Nullable<decimal> _percentageDifference;
		
		private System.Nullable<int> _amountDifference;
		
		public GetCampVarianceReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseNumber", DbType="VarChar(50)")]
		public string licenseNumber
		{
			get
			{
				return this._licenseNumber;
			}
			set
			{
				if ((this._licenseNumber != value))
				{
					this._licenseNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if ((this._productName != value))
				{
					this._productName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_communityName", DbType="VarChar(50)")]
		public string communityName
		{
			get
			{
				return this._communityName;
			}
			set
			{
				if ((this._communityName != value))
				{
					this._communityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionName", DbType="VarChar(100)")]
		public string regionName
		{
			get
			{
				return this._regionName;
			}
			set
			{
				if ((this._regionName != value))
				{
					this._regionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startUnitsSold", DbType="Int")]
		public System.Nullable<int> startUnitsSold
		{
			get
			{
				return this._startUnitsSold;
			}
			set
			{
				if ((this._startUnitsSold != value))
				{
					this._startUnitsSold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endUnitsSold", DbType="Int")]
		public System.Nullable<int> endUnitsSold
		{
			get
			{
				return this._endUnitsSold;
			}
			set
			{
				if ((this._endUnitsSold != value))
				{
					this._endUnitsSold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentageDifference", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> percentageDifference
		{
			get
			{
				return this._percentageDifference;
			}
			set
			{
				if ((this._percentageDifference != value))
				{
					this._percentageDifference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amountDifference", DbType="Int")]
		public System.Nullable<int> amountDifference
		{
			get
			{
				return this._amountDifference;
			}
			set
			{
				if ((this._amountDifference != value))
				{
					this._amountDifference = value;
				}
			}
		}
	}
	
	public partial class CalculateOpenPropertiesResult
	{
		
		private int _id;
		
		public CalculateOpenPropertiesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
